name: binapm_cli
description: A project and workspace manager for various technologies and IDEs.

homepage: https://softyes.com.br
repository: https://github.com/BinaPM/binapm_cli

version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  very_good_analysis: ^10.0.0
